apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-galaxy
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/k8s/volumes/galaxy_data"