## Here, helm keeps track of the dependencies that are required for the
## application. Dependencies should be listed here, then the dependencies
## updated with:
##
##    helm dep update
##
## and the requirements.lock file committed.
# version: 5.3.6
dependencies:
    - name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.0.0
      condition: postgresql.enabled
